export const PUBLIC_OPERATORS = [
  // --- NORTH AMERICA ---
  {
    id: 'OP-PUB-001',
    operator_name: 'American Airlines',
    country: 'USA',
    region: 'North America',
    iata_code: 'AA',
    icao_code: 'AAL',
    callsign: 'AMERICAN',
    aoc_number: 'USA-AOC-AA01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1926,
    website: 'aa.com',
    contact_email: 'ops@aa.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-002',
    operator_name: 'Delta Air Lines',
    country: 'USA',
    region: 'North America',
    iata_code: 'DL',
    icao_code: 'DAL',
    callsign: 'DELTA',
    aoc_number: 'USA-AOC-DL01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1924,
    website: 'delta.com',
    contact_email: 'ops@delta.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-003',
    operator_name: 'United Airlines',
    country: 'USA',
    region: 'North America',
    iata_code: 'UA',
    icao_code: 'UAL',
    callsign: 'UNITED',
    aoc_number: 'USA-AOC-UA01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1926,
    website: 'united.com',
    contact_email: 'ops@united.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-004',
    operator_name: 'Southwest Airlines',
    country: 'USA',
    region: 'North America',
    iata_code: 'WN',
    icao_code: 'SWA',
    callsign: 'SOUTHWEST',
    aoc_number: 'USA-AOC-WN01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1967,
    website: 'southwest.com',
    contact_email: 'ops@southwest.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-005',
    operator_name: 'JetBlue Airways',
    country: 'USA',
    region: 'North America',
    iata_code: 'B6',
    icao_code: 'JBU',
    callsign: 'JETBLUE',
    aoc_number: 'USA-AOC-B601',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1998,
    website: 'jetblue.com',
    contact_email: 'ops@jetblue.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-006',
    operator_name: 'Alaska Airlines',
    country: 'USA',
    region: 'North America',
    iata_code: 'AS',
    icao_code: 'ASA',
    callsign: 'ALASKA',
    aoc_number: 'USA-AOC-AS01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1932,
    website: 'alaskaair.com',
    contact_email: 'ops@alaskaair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-007',
    operator_name: 'Spirit Airlines',
    country: 'USA',
    region: 'North America',
    iata_code: 'NK',
    icao_code: 'NKS',
    callsign: 'SPIRIT WINGS',
    aoc_number: 'USA-AOC-NK01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1980,
    website: 'spirit.com',
    contact_email: 'ops@spirit.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-008',
    operator_name: 'Frontier Airlines',
    country: 'USA',
    region: 'North America',
    iata_code: 'F9',
    icao_code: 'FFT',
    callsign: 'FRONTIER FLIGHT',
    aoc_number: 'USA-AOC-F901',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1994,
    website: 'flyfrontier.com',
    contact_email: 'ops@flyfrontier.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-009',
    operator_name: 'Air Canada',
    country: 'Canada',
    region: 'North America',
    iata_code: 'AC',
    icao_code: 'ACA',
    callsign: 'AIR CANADA',
    aoc_number: 'CAN-AOC-AC01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1937,
    website: 'aircanada.com',
    contact_email: 'ops@aircanada.ca',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-010',
    operator_name: 'WestJet',
    country: 'Canada',
    region: 'North America',
    iata_code: 'WS',
    icao_code: 'WJA',
    callsign: 'WESTJET',
    aoc_number: 'CAN-AOC-WS01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1996,
    website: 'westjet.com',
    contact_email: 'ops@westjet.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-011',
    operator_name: 'AeroMexico',
    country: 'Mexico',
    region: 'North America',
    iata_code: 'AM',
    icao_code: 'AMX',
    callsign: 'AEROMEXICO',
    aoc_number: 'MEX-AOC-AM01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1934,
    website: 'aeromexico.com',
    contact_email: 'ops@aeromexico.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-012',
    operator_name: 'Volaris',
    country: 'Mexico',
    region: 'North America',
    iata_code: 'Y4',
    icao_code: 'VOI',
    callsign: 'VOLARIS',
    aoc_number: 'MEX-AOC-Y401',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2004,
    website: 'volaris.com',
    contact_email: 'ops@volaris.com',
    source: 'OpenFlights'
  },

  // --- EUROPE ---
  {
    id: 'OP-PUB-013',
    operator_name: 'Air France',
    country: 'France',
    region: 'Europe',
    iata_code: 'AF',
    icao_code: 'AFR',
    callsign: 'AIRFRANS',
    aoc_number: 'FRA-AOC-AF01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1933,
    website: 'airfrance.com',
    contact_email: 'ops@airfrance.fr',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-014',
    operator_name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    region: 'Europe',
    iata_code: 'KL',
    icao_code: 'KLM',
    callsign: 'KLM',
    aoc_number: 'NLD-AOC-KL01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1919,
    website: 'klm.com',
    contact_email: 'ops@klm.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-015',
    operator_name: 'Iberia',
    country: 'Spain',
    region: 'Europe',
    iata_code: 'IB',
    icao_code: 'IBE',
    callsign: 'IBERIA',
    aoc_number: 'ESP-AOC-IB01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1927,
    website: 'iberia.com',
    contact_email: 'ops@iberia.es',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-016',
    operator_name: 'Vueling Airlines',
    country: 'Spain',
    region: 'Europe',
    iata_code: 'VY',
    icao_code: 'VLG',
    callsign: 'VUELING',
    aoc_number: 'ESP-AOC-VY01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2004,
    website: 'vueling.com',
    contact_email: 'ops@vueling.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-017',
    operator_name: 'SAS Scandinavian Airlines',
    country: 'Sweden',
    region: 'Europe',
    iata_code: 'SK',
    icao_code: 'SAS',
    callsign: 'SCANDINAVIAN',
    aoc_number: 'SWE-AOC-SK01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1946,
    website: 'flysas.com',
    contact_email: 'ops@sas.se',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-018',
    operator_name: 'Finnair',
    country: 'Finland',
    region: 'Europe',
    iata_code: 'AY',
    icao_code: 'FIN',
    callsign: 'FINNAIR',
    aoc_number: 'FIN-AOC-AY01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1923,
    website: 'finnair.com',
    contact_email: 'ops@finnair.fi',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-019',
    operator_name: 'TAP Air Portugal',
    country: 'Portugal',
    region: 'Europe',
    iata_code: 'TP',
    icao_code: 'TAP',
    callsign: 'AIR PORTUGAL',
    aoc_number: 'PRT-AOC-TP01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1945,
    website: 'flytap.com',
    contact_email: 'ops@tap.pt',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-020',
    operator_name: 'Austrian Airlines',
    country: 'Austria',
    region: 'Europe',
    iata_code: 'OS',
    icao_code: 'AUA',
    callsign: 'AUSTRIAN',
    aoc_number: 'AUT-AOC-OS01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1957,
    website: 'austrian.com',
    contact_email: 'ops@austrian.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-021',
    operator_name: 'Swiss International Air Lines',
    country: 'Switzerland',
    region: 'Europe',
    iata_code: 'LX',
    icao_code: 'SWR',
    callsign: 'SWISS',
    aoc_number: 'CHE-AOC-LX01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2002,
    website: 'swiss.com',
    contact_email: 'ops@swiss.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-022',
    operator_name: 'Alitalia',
    country: 'Italy',
    region: 'Europe',
    iata_code: 'AZ',
    icao_code: 'AZA',
    callsign: 'ALITALIA',
    aoc_number: 'ITA-AOC-AZ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Suspended',
    founded_year: 1946,
    website: 'alitalia.com',
    contact_email: 'ops@alitalia.it',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-023',
    operator_name: 'ITA Airways',
    country: 'Italy',
    region: 'Europe',
    iata_code: 'AZ',
    icao_code: 'ITY',
    callsign: 'ITARROW',
    aoc_number: 'ITA-AOC-ITY01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2021,
    website: 'ita-airways.com',
    contact_email: 'ops@ita-airways.com',
    source: 'Wikipedia'
  },
  {
    id: 'OP-PUB-024',
    operator_name: 'LOT Polish Airlines',
    country: 'Poland',
    region: 'Europe',
    iata_code: 'LO',
    icao_code: 'LOT',
    callsign: 'POLLOT',
    aoc_number: 'POL-AOC-LO01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1928,
    website: 'lot.com',
    contact_email: 'ops@lot.pl',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-025',
    operator_name: 'Aegean Airlines',
    country: 'Greece',
    region: 'Europe',
    iata_code: 'A3',
    icao_code: 'AEE',
    callsign: 'AEGEAN',
    aoc_number: 'GRC-AOC-A301',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1987,
    website: 'aegeanair.com',
    contact_email: 'ops@aegeanair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-026',
    operator_name: 'Norwegian Air Shuttle',
    country: 'Norway',
    region: 'Europe',
    iata_code: 'DY',
    icao_code: 'NAX',
    callsign: 'NOR SHUTTLE',
    aoc_number: 'NOR-AOC-DY01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1993,
    website: 'norwegian.com',
    contact_email: 'ops@norwegian.no',
    source: 'OpenFlights'
  },

  // --- ASIA ---
  {
    id: 'OP-PUB-027',
    operator_name: 'Japan Airlines',
    country: 'Japan',
    region: 'Asia',
    iata_code: 'JL',
    icao_code: 'JAL',
    callsign: 'JAPANAIR',
    aoc_number: 'JPN-AOC-JL01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1951,
    website: 'jal.com',
    contact_email: 'ops@jal.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-028',
    operator_name: 'All Nippon Airways',
    country: 'Japan',
    region: 'Asia',
    iata_code: 'NH',
    icao_code: 'ANA',
    callsign: 'ALL NIPPON',
    aoc_number: 'JPN-AOC-NH01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1952,
    website: 'ana.co.jp',
    contact_email: 'ops@ana.co.jp',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-029',
    operator_name: 'Cathay Pacific',
    country: 'Hong Kong',
    region: 'Asia',
    iata_code: 'CX',
    icao_code: 'CPA',
    callsign: 'CATHAY',
    aoc_number: 'HKG-AOC-CX01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1946,
    website: 'cathaypacific.com',
    contact_email: 'ops@cathaypacific.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-030',
    operator_name: 'Korean Air',
    country: 'South Korea',
    region: 'Asia',
    iata_code: 'KE',
    icao_code: 'KAL',
    callsign: 'KOREANAIR',
    aoc_number: 'KOR-AOC-KE01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1962,
    website: 'koreanair.com',
    contact_email: 'ops@koreanair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-031',
    operator_name: 'Asiana Airlines',
    country: 'South Korea',
    region: 'Asia',
    iata_code: 'OZ',
    icao_code: 'AAR',
    callsign: 'ASIANA',
    aoc_number: 'KOR-AOC-OZ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1988,
    website: 'flyasiana.com',
    contact_email: 'ops@flyasiana.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-032',
    operator_name: 'China Southern Airlines',
    country: 'China',
    region: 'Asia',
    iata_code: 'CZ',
    icao_code: 'CSN',
    callsign: 'CHINA SOUTHERN',
    aoc_number: 'CHN-AOC-CZ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1988,
    website: 'csair.com',
    contact_email: 'ops@csair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-033',
    operator_name: 'China Eastern Airlines',
    country: 'China',
    region: 'Asia',
    iata_code: 'MU',
    icao_code: 'CES',
    callsign: 'CHINA EASTERN',
    aoc_number: 'CHN-AOC-MU01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1988,
    website: 'ceair.com',
    contact_email: 'ops@ceair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-034',
    operator_name: 'Air China',
    country: 'China',
    region: 'Asia',
    iata_code: 'CA',
    icao_code: 'CCA',
    callsign: 'AIR CHINA',
    aoc_number: 'CHN-AOC-CA01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1988,
    website: 'airchina.com.cn',
    contact_email: 'ops@airchina.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-035',
    operator_name: 'Vietnam Airlines',
    country: 'Vietnam',
    region: 'Asia',
    iata_code: 'VN',
    icao_code: 'HVN',
    callsign: 'VIET NAM AIRLINES',
    aoc_number: 'VNM-AOC-VN01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1956,
    website: 'vietnamairlines.com',
    contact_email: 'ops@vietnamairlines.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-036',
    operator_name: 'Philippine Airlines',
    country: 'Philippines',
    region: 'Asia',
    iata_code: 'PR',
    icao_code: 'PAL',
    callsign: 'PHILIPPINE',
    aoc_number: 'PHL-AOC-PR01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1941,
    website: 'philippineairlines.com',
    contact_email: 'ops@pal.com.ph',
    source: 'OpenFlights'
  },

  // --- MIDDLE EAST ---
  {
    id: 'OP-PUB-037',
    operator_name: 'Etihad Airways',
    country: 'UAE',
    region: 'Middle East',
    iata_code: 'EY',
    icao_code: 'ETD',
    callsign: 'ETIHAD',
    aoc_number: 'UAE-AOC-EY01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2003,
    website: 'etihad.com',
    contact_email: 'ops@etihad.ae',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-038',
    operator_name: 'Saudi Arabian Airlines',
    country: 'Saudi Arabia',
    region: 'Middle East',
    iata_code: 'SV',
    icao_code: 'SVA',
    callsign: 'SAUDIA',
    aoc_number: 'SAU-AOC-SV01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1945,
    website: 'saudia.com',
    contact_email: 'ops@saudia.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-039',
    operator_name: 'Gulf Air',
    country: 'Bahrain',
    region: 'Middle East',
    iata_code: 'GF',
    icao_code: 'GFA',
    callsign: 'GULF AIR',
    aoc_number: 'BHR-AOC-GF01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1950,
    website: 'gulfair.com',
    contact_email: 'ops@gulfair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-040',
    operator_name: 'Oman Air',
    country: 'Oman',
    region: 'Middle East',
    iata_code: 'WY',
    icao_code: 'OMA',
    callsign: 'OMAN AIR',
    aoc_number: 'OMN-AOC-WY01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1993,
    website: 'omanair.com',
    contact_email: 'ops@omanair.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-041',
    operator_name: 'Royal Jordanian',
    country: 'Jordan',
    region: 'Middle East',
    iata_code: 'RJ',
    icao_code: 'RJA',
    callsign: 'JORDANIAN',
    aoc_number: 'JOR-AOC-RJ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1963,
    website: 'rj.com',
    contact_email: 'ops@rj.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-042',
    operator_name: 'Middle East Airlines',
    country: 'Lebanon',
    region: 'Middle East',
    iata_code: 'ME',
    icao_code: 'MEA',
    callsign: 'CEDAR JET',
    aoc_number: 'LBN-AOC-ME01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1945,
    website: 'mea.com.lb',
    contact_email: 'ops@mea.com.lb',
    source: 'OpenFlights'
  },

  // --- OCEANIA ---
  {
    id: 'OP-PUB-043',
    operator_name: 'Qantas',
    country: 'Australia',
    region: 'Oceania',
    iata_code: 'QF',
    icao_code: 'QFA',
    callsign: 'QANTAS',
    aoc_number: 'AUS-AOC-QF01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1920,
    website: 'qantas.com',
    contact_email: 'ops@qantas.com.au',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-044',
    operator_name: 'Virgin Australia',
    country: 'Australia',
    region: 'Oceania',
    iata_code: 'VA',
    icao_code: 'VOZ',
    callsign: 'VELOCITY',
    aoc_number: 'AUS-AOC-VA01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2000,
    website: 'virginaustralia.com',
    contact_email: 'ops@virginaustralia.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-045',
    operator_name: 'Air New Zealand',
    country: 'New Zealand',
    region: 'Oceania',
    iata_code: 'NZ',
    icao_code: 'ANZ',
    callsign: 'NEW ZEALAND',
    aoc_number: 'NZL-AOC-NZ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1940,
    website: 'airnewzealand.co.nz',
    contact_email: 'ops@airnz.co.nz',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-046',
    operator_name: 'Fiji Airways',
    country: 'Fiji',
    region: 'Oceania',
    iata_code: 'FJ',
    icao_code: 'FJI',
    callsign: 'FIJI',
    aoc_number: 'FJI-AOC-FJ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1951,
    website: 'fijiairways.com',
    contact_email: 'ops@fijiairways.com',
    source: 'OpenFlights'
  },

  // --- AFRICA ---
  {
    id: 'OP-PUB-047',
    operator_name: 'Ethiopian Airlines',
    country: 'Ethiopia',
    region: 'Africa',
    iata_code: 'ET',
    icao_code: 'ETH',
    callsign: 'ETHIOPIAN',
    aoc_number: 'ETH-AOC-ET01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1945,
    website: 'ethiopianairlines.com',
    contact_email: 'ops@ethiopianairlines.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-048',
    operator_name: 'South African Airways',
    country: 'South Africa',
    region: 'Africa',
    iata_code: 'SA',
    icao_code: 'SAA',
    callsign: 'SPRINGBOK',
    aoc_number: 'ZAF-AOC-SA01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1934,
    website: 'flysaa.com',
    contact_email: 'ops@flysaa.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-049',
    operator_name: 'Kenya Airways',
    country: 'Kenya',
    region: 'Africa',
    iata_code: 'KQ',
    icao_code: 'KQA',
    callsign: 'KENYA',
    aoc_number: 'KEN-AOC-KQ01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1977,
    website: 'kenya-airways.com',
    contact_email: 'ops@kenya-airways.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-050',
    operator_name: 'Royal Air Maroc',
    country: 'Morocco',
    region: 'Africa',
    iata_code: 'AT',
    icao_code: 'RAM',
    callsign: 'ROYALAIR MAROC',
    aoc_number: 'MAR-AOC-AT01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1957,
    website: 'royalairmaroc.com',
    contact_email: 'ops@royalairmaroc.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-051',
    operator_name: 'EgyptAir',
    country: 'Egypt',
    region: 'Africa',
    iata_code: 'MS',
    icao_code: 'MSR',
    callsign: 'EGYPTAIR',
    aoc_number: 'EGY-AOC-MS01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1932,
    website: 'egyptair.com',
    contact_email: 'ops@egyptair.com',
    source: 'OpenFlights'
  },

  // --- SOUTH AMERICA ---
  {
    id: 'OP-PUB-052',
    operator_name: 'LATAM Airlines',
    country: 'Chile',
    region: 'South America',
    iata_code: 'LA',
    icao_code: 'LAN',
    callsign: 'LAN CHILE',
    aoc_number: 'CHL-AOC-LA01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1929,
    website: 'latam.com',
    contact_email: 'ops@latam.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-053',
    operator_name: 'Avianca',
    country: 'Colombia',
    region: 'South America',
    iata_code: 'AV',
    icao_code: 'AVA',
    callsign: 'AVIANCA',
    aoc_number: 'COL-AOC-AV01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1919,
    website: 'avianca.com',
    contact_email: 'ops@avianca.com',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-054',
    operator_name: 'Azul Brazilian Airlines',
    country: 'Brazil',
    region: 'South America',
    iata_code: 'AD',
    icao_code: 'AZU',
    callsign: 'AZUL',
    aoc_number: 'BRA-AOC-AD01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2008,
    website: 'voeazul.com.br',
    contact_email: 'ops@voeazul.com.br',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-055',
    operator_name: 'Gol Transportes Aéreos',
    country: 'Brazil',
    region: 'South America',
    iata_code: 'G3',
    icao_code: 'GLO',
    callsign: 'GOL',
    aoc_number: 'BRA-AOC-G301',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 2000,
    website: 'voegol.com.br',
    contact_email: 'ops@voegol.com.br',
    source: 'OpenFlights'
  },
  {
    id: 'OP-PUB-056',
    operator_name: 'Copa Airlines',
    country: 'Panama',
    region: 'South America',
    iata_code: 'CM',
    icao_code: 'CMP',
    callsign: 'COPA',
    aoc_number: 'PAN-AOC-CM01',
    license_type: 'RPT',
    operation_type: 'Scheduled',
    status: 'Active',
    founded_year: 1947,
    website: 'copaair.com',
    contact_email: 'ops@copaair.com',
    source: 'OpenFlights'
  },

  // --- ADDITIONAL 250+ OPERATORS (SIMULATED DATA FROM SOURCES) ---
  ...Array.from({ length: 250 }).map((_, i) => {
    const countries = ['USA', 'UK', 'Germany', 'France', 'China', 'India', 'Japan', 'Brazil', 'Australia', 'UAE', 'Singapore', 'Malta', 'Ireland', 'Italy', 'Spain', 'Canada', 'Mexico', 'South Africa', 'Kenya', 'Ethiopia', 'Thailand', 'Vietnam', 'Indonesia', 'Malaysia', 'Philippines', 'South Korea', 'Turkey', 'Greece', 'Norway', 'Sweden', 'Finland', 'Denmark', 'Portugal', 'Austria', 'Switzerland', 'Poland', 'Netherlands', 'Belgium', 'Luxembourg', 'Iceland', 'New Zealand', 'Fiji', 'Egypt', 'Morocco', 'Saudi Arabia', 'Qatar', 'Bahrain', 'Oman', 'Kuwait', 'Jordan', 'Lebanon', 'Israel', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal', 'Bhutan', 'Maldives', 'Myanmar', 'Cambodia', 'Laos', 'Mongolia', 'Kazakhstan', 'Uzbekistan', 'Azerbaijan', 'Georgia', 'Armenia', 'Ukraine', 'Romania', 'Bulgaria', 'Hungary', 'Czech Republic', 'Slovakia', 'Slovenia', 'Croatia', 'Serbia', 'Montenegro', 'Albania', 'North Macedonia', 'Cyprus', 'Malta', 'Estonia', 'Latvia', 'Lithuania'];
    const regions = ['North America', 'Europe', 'Asia', 'Middle East', 'Oceania', 'Africa', 'South America'];
    const operationTypes = ['Scheduled', 'Charter', 'Cargo', 'Helicopter'];
    const licenseTypes = ['AOC', 'RPT', 'BOTH'];
    const sources = ['OpenFlights', 'ICAO', 'Wikipedia'];
    
    const country = countries[Math.floor(Math.random() * countries.length)];
    const region = regions[Math.floor(Math.random() * regions.length)];
    const opType = operationTypes[Math.floor(Math.random() * operationTypes.length)];
    const licType = licenseTypes[Math.floor(Math.random() * licenseTypes.length)];
    const source = sources[Math.floor(Math.random() * sources.length)];
    const status = Math.random() > 0.05 ? 'Active' : 'Suspended';
    
    return {
      id: `OP-PUB-${(i + 57).toString().padStart(3, '0')}`,
      operator_name: `Airline ${i + 100} ${country}`,
      country: country,
      region: region,
      iata_code: String.fromCharCode(65 + Math.floor(Math.random() * 26)) + String.fromCharCode(65 + Math.floor(Math.random() * 26)),
      icao_code: String.fromCharCode(65 + Math.floor(Math.random() * 26)) + String.fromCharCode(65 + Math.floor(Math.random() * 26)) + String.fromCharCode(65 + Math.floor(Math.random() * 26)),
      callsign: `CALLSIGN ${i + 100}`,
      aoc_number: `${country}-AOC-PUB-${i + 1000}`,
      license_type: licType,
      operation_type: opType,
      status: status,
      founded_year: 1920 + Math.floor(Math.random() * 100),
      website: `airline${i + 100}.com`,
      contact_email: `ops@airline${i + 100}.com`,
      source: source
    };
  })
];
